'use strict';
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('pt-BR'),norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const data=window.MAP_DATA.locais,profiles=window.MAP_DATA.municipios;
const searchIndex=new Map(data.map(r=>[r.id,norm([r.nome,r.endereco,r.bairro,r.municipio,r.cep,r.zona].join(' '))]));
const searchLink=r=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(`${r.endereco}, ${r.bairro}, ${r.municipio}, RJ, Brasil`);
function selectRows(rows,f){return rows.filter(r=>(!f.municipio||r.municipio===f.municipio)&&(!f.bairro||r.bairro===f.bairro)&&(!f.zona||r.zona===f.zona)&&(!f.status||r.status===f.status)&&r.eleitores>=f.min&&r.eleitores<=f.max&&r.qtdSecoes>=f.secoes&&(!f.q||searchIndex.get(r.id).includes(norm(f.q))))}
const defaults={municipio:'',bairro:'',zona:'',status:'',min:0,max:Infinity,secoes:0,q:''};
function currentFilters(){return{municipio:$('municipio').value,bairro:$('bairro').value,zona:$('zona').value,status:$('status').value,min:$('min').value===''?0:Number($('min').value),max:$('max').value===''?Infinity:Number($('max').value),secoes:Number($('secoes').value)||0,q:$('search').value.trim()}}
function options(id,values,label){const s=$(id),old=s.value;s.replaceChildren(new Option(label,''));for(const v of [...new Set(values)].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true})))s.add(new Option(v,v));if([...s.options].some(o=>o.value===old))s.value=old}
options('municipio',data.map(r=>r.municipio),'Todo o estado');
function dependentOptions(){const rows=data.filter(r=>!$('municipio').value||r.municipio===$('municipio').value);options('bairro',rows.map(r=>r.bairro),'Todos os bairros');options('zona',rows.map(r=>r.zona),'Todas as zonas')}
dependentOptions();
let map,clusters,filtered=[],limit=60;const markers=new Map();
if(typeof L!=='undefined'&&L.markerClusterGroup){map=L.map('map').setView([-22.25,-42.6],8);const tiles=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,maxNativeZoom:18,attribution:'Tiles © Esri — Esri, HERE, Garmin, USGS, Intermap, INCREMENT P, NRCAN, Esri Japan, METI, Esri China (Hong Kong), OpenStreetMap contributors, GIS User Community | Geocodificação: Esri'}).addTo(map);let errors=0;tiles.on('tileerror',()=>{if(++errors>=3)$('tile-error').hidden=false});tiles.on('tileload',()=>{$('tile-error').hidden=true;errors=0});clusters=L.markerClusterGroup({maxClusterRadius:48}).addTo(map);for(const r of data.filter(r=>r.lat!=null)){const color=r.status==='Aproximado'?'#dc8b19':'#2478bb';const marker=L.marker([r.lat,r.lon],{icon:L.divIcon({className:'',html:`<div style="background:${color};width:16px;height:16px;border:2px solid white;border-radius:50%;box-shadow:0 1px 5px #555"></div>`,iconSize:[16,16],iconAnchor:[8,8]})});marker.bindPopup(()=>`<h3>${esc(r.nome)}</h3>${esc(r.endereco)}<br>${esc(r.bairro)} · ${esc(r.municipio)}<br>CEP: ${esc(r.cep)}<hr><b>${fmt(r.eleitores)} eleitores aptos</b><br>${fmt(r.qtdSecoes)} seções · Zona ${esc(r.zona)} · Local ${esc(r.local)}<br><small>Seções: ${esc(r.secoes.join(', '))}</small><hr>${esc(r.status)}<br><small>Correspondência: ${esc(r.correspondencia)}</small><br><a href="${searchLink(r)}" target="_blank" rel="noopener">Conferir no Google Maps</a>`);markers.set(r.id,marker)}}else{$('tile-error').hidden=false;$('tile-error').textContent='Não foi possível carregar o mapa. Verifique sua conexão. A lista e os filtros continuam disponíveis.'}
function fit(){if(clusters&&clusters.getLayers().length)map.fitBounds(clusters.getBounds(),{padding:[30,30],maxZoom:15})}
function focus(r){if(markers.has(r.id))clusters.zoomToShowLayer(markers.get(r.id),()=>markers.get(r.id).openPopup())}
function badge(r){return`<span class="badge ${r.status==='Aproximado'?'approx':r.lat==null?'missing':''}">${esc(r.status)}</span>`}
function drawList(){const fragment=document.createDocumentFragment();for(const r of filtered.slice(0,limit)){const a=document.createElement('article');a.innerHTML=`<button type="button">${esc(r.nome)}</button><p>${esc(r.endereco)}<br>${esc(r.municipio)} · ${esc(r.bairro)} · Zona ${esc(r.zona)}</p><p class="numbers">${fmt(r.eleitores)} eleitores · ${fmt(r.qtdSecoes)} seções</p>${badge(r)}`;a.querySelector('button').onclick=()=>focus(r);if(!markers.has(r.id)){const link=document.createElement('a');link.href=searchLink(r);link.target='_blank';link.rel='noopener';link.textContent=' Conferir endereço';a.append(link)}fragment.append(a)}if(!filtered.length){const p=document.createElement('p');p.className='empty';p.textContent='Nenhum local corresponde aos filtros. Ajuste os valores ou limpe os filtros.';fragment.append(p)}if(filtered.length>limit){const b=document.createElement('button');b.className='more secondary';b.textContent=`Mostrar mais (${fmt(filtered.length-limit)} restantes)`;b.onclick=()=>{limit+=60;drawList()};fragment.append(b)}$('list').replaceChildren(fragment)}
function chart(title,obj){if(!obj)return '';const entries=Object.entries(obj),max=Math.max(...entries.map(([,n])=>n),1);return`<h3>${esc(title)}</h3>`+entries.map(([label,n])=>`<div class="bar-row"><span>${esc(label)}</span><b>${fmt(n)}</b><div class="bar"><i style="width:${100*n/max}%"></i></div></div>`).join('')}
function profile(){const name=$('municipio').value,p=profiles[name];$('profile').hidden=!p;if(!p)return;$('profile-title').textContent=`Perfil: ${name}`;$('profile-body').innerHTML=`<p>Totais do município inteiro; não mudam com os filtros de local.</p><b>${fmt(p.eleitores)} eleitores · ${fmt(p.locais)} locais</b>${chart('Sexo cadastrado',p.sexo)}${chart('Faixa etária',p.idade)}${chart('Grau de instrução',p.instrucao)}<h3>Eleitores com deficiência registrada</h3><p>${fmt(p.deficiencia?.QTD_DEFICIENCIA||0)} no município. Este dado não mede a acessibilidade dos locais.</p>`}
function render(autoFit=false){const f=currentFilters();const invalid=f.min<0||f.max<0||f.min>f.max||f.secoes<0||![f.min,f.secoes].every(Number.isInteger)||(f.max!==Infinity&&!Number.isInteger(f.max));$('error').textContent=invalid?'Use números inteiros não negativos e mínimo menor ou igual ao máximo.':'';filtered=invalid?[]:selectRows(data,f);const sort=$('sort').value;filtered.sort(sort==='name'?(a,b)=>a.nome.localeCompare(b.nome,'pt-BR'):(a,b)=>(sort==='asc'?a.eleitores-b.eleitores:b.eleitores-a.eleitores)||a.nome.localeCompare(b.nome,'pt-BR'));limit=60;const located=filtered.filter(r=>r.lat!=null);if(clusters){clusters.clearLayers();clusters.addLayers(located.map(r=>markers.get(r.id)))}$('count').textContent=`${fmt(filtered.length)} locais encontrados`;$('voters').textContent=`${fmt(filtered.reduce((sum,r)=>sum+r.eleitores,0))} eleitores nos locais filtrados`;$('coverage').textContent=`${fmt(located.length)} no mapa · ${fmt(filtered.length-located.length)} sem posição · ${fmt(filtered.filter(r=>r.status==='Aproximado').length)} aproximados`;$('fit').disabled=!located.length;drawList();profile();if(autoFit)fit()}
$('municipio').onchange=()=>{$('bairro').value='';$('zona').value='';dependentOptions();render(true)};for(const id of ['bairro','zona','status'])$(id).onchange=()=>render(true);let timer;for(const id of ['search','min','max','secoes'])$(id).oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>render(),200)};$('sort').onchange=()=>render();$('fit').onclick=fit;$('clear').onclick=()=>{clearTimeout(timer);for(const id of ['search','municipio','bairro','zona','status','min','max','secoes'])$(id).value='';dependentOptions();render(true)};
$('export').onclick=()=>{const cols=['nome','endereco','bairro','municipio','zona','local','cep','eleitores','qtdSecoes','status','lat','lon'];const safe=v=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const csv='\uFEFF'+[cols.join(';'),...filtered.map(r=>cols.map(c=>safe(r[c])).join(';'))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='locais-filtrados.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
render(true);
if(new URLSearchParams(location.search).has('test')){const assertions=[];const assert=(name,value)=>{assertions.push({name,ok:!!value});if(!value)console.error(name)};assert('5040 locais',data.length===5040);assert('92 municipios',new Set(data.map(r=>r.municipio)).size===92);assert('12857388 eleitores',data.reduce((s,r)=>s+r.eleitores,0)===12857388);for(const m of ['RIO DE JANEIRO','NITERÓI']){const rows=selectRows(data,{...defaults,municipio:m});assert('total municipal '+m,rows.length===profiles[m].locais&&rows.reduce((s,r)=>s+r.eleitores,0)===profiles[m].eleitores)}const sample=data.find(r=>r.municipio==='NITERÓI');const exact=selectRows(data,{...defaults,municipio:sample.municipio,min:sample.eleitores,max:sample.eleitores});assert('limites inclusivos',exact.some(r=>r.id===sample.id)&&exact.every(r=>r.eleitores===sample.eleitores));assert('busca sem acento',selectRows(data,{...defaults,municipio:'NITERÓI',q:'niteroi'}).length===profiles['NITERÓI'].locais);$('municipio').value='NITERÓI';$('municipio').dispatchEvent(new Event('change'));assert('bairros dependentes',[...$('bairro').options].slice(1).every(o=>data.some(r=>r.municipio==='NITERÓI'&&r.bairro===o.value)));$('min').value='5000';$('max').value='1000';render();assert('intervalo invalido',filtered.length===0&&$('error').textContent.length>0);$('clear').click();assert('limpar filtros',filtered.length===5040);assert('mapa inicializado',!!map&&markers.size===data.filter(r=>r.lat!=null).length);const el=document.createElement('pre');el.id='test-results';el.hidden=true;el.textContent=JSON.stringify(assertions);document.body.append(el);document.title=assertions.every(a=>a.ok)?'TESTS PASS':'TESTS FAIL';}
